CREATE PROC uspAddCNPCKClient
AS
	ALTER TABLE Client
	ADD CNP varchar(30)
	ALTER TABLE Client
	ADD CONSTRAINT CK_CNP UNIQUE(CNP);
GO;

CREATE PROC uspRemoveCNPCKClient
AS
	ALTER TABLE Client
	DROP CONSTRAINT CK_CNP;
	ALTER TABLE Client
	DROP COLUMN CNP
